# Generated by Django 4.2.30 on 2026-09-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Constellation and SolarSystem are both defined in eve_sde's first
        # migration; depend on that rather than "whatever is latest" so this
        # doesn't churn every time eve_sde ships new, unrelated migrations.
        ("eve_sde", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Effect",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShatteredConstellation",
            fields=[
                (
                    "constellation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="eve_sde.constellation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WormholeClass",
            fields=[
                (
                    "class_id",
                    models.IntegerField(
                        help_text="EVE SDE wormholeClassID, matches eve_sde.SolarSystem.wormhole_class_id_raw.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=20, unique=True)),
                ("short_name", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("short_title", models.CharField(max_length=30)),
                (
                    "effect_power",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-6 index into an Effect's per-strength modifier list for systems of this class.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("numbered", "Numbered (C1-C6)"),
                            ("shattered_frigate", "Shattered frigate hole (C13)"),
                            ("drifter", "Drifter space (C14-C18)"),
                            ("thera", "Thera"),
                            ("abyssal", "Abyssal Deadspace"),
                            ("known_space", "High/Low/Null-sec"),
                            ("pochven", "Pochven"),
                            ("pirate", "Pirate space (Zarzakh)"),
                            ("reverse", "Reverse signature marker (K162)"),
                            ("ccp", "CCP-reserved / test system"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "wormhole class",
                "verbose_name_plural": "wormhole classes",
                "ordering": ["class_id"],
            },
        ),
        migrations.CreateModel(
            name="WormholeType",
            fields=[
                (
                    "code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                (
                    "lifetime_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("total_mass", models.BigIntegerField(blank=True, null=True)),
                ("max_jump_mass", models.BigIntegerField(blank=True, null=True)),
                ("mass_regeneration", models.BigIntegerField(blank=True, null=True)),
                (
                    "is_static_capable",
                    models.BooleanField(
                        default=False,
                        help_text="Can this type appear as a system's permanent static.",
                    ),
                ),
                (
                    "can_be_wandering",
                    models.BooleanField(
                        default=False,
                        help_text="Can this type appear as a random (non-static) signature.",
                    ),
                ),
                (
                    "is_reverse_signature",
                    models.BooleanField(
                        default=False,
                        help_text="K162: the generic signature seen on the far side of any wormhole.",
                    ),
                ),
                ("spawns_in_shattered_system", models.BooleanField(default=False)),
                ("spawns_at_jovian_observatory", models.BooleanField(default=False)),
                (
                    "leads_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wormhole_types_leading_here",
                        to="wormholes.wormholeclass",
                    ),
                ),
                (
                    "spawns_in",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wormhole_types_spawning_here",
                        to="wormholes.wormholeclass",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="WormholeSystem",
            fields=[
                (
                    "solar_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wormhole_info",
                        serialize=False,
                        to="eve_sde.solarsystem",
                    ),
                ),
                (
                    "effect_power",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Overrides the class's effect_power. Only set for Pochven systems, whose effect strength depends on invasion history rather than wormhole class.",
                        null=True,
                    ),
                ),
                ("invasion_status", models.CharField(blank=True, max_length=20)),
                (
                    "effect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="systems",
                        to="wormholes.effect",
                    ),
                ),
                (
                    "statics",
                    models.ManyToManyField(
                        blank=True,
                        related_name="static_in_systems",
                        to="wormholes.wormholetype",
                    ),
                ),
                (
                    "wandering_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wandering_in_systems",
                        to="wormholes.wormholetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "wormhole system",
                "verbose_name_plural": "wormhole systems",
                "ordering": ["solar_system__name"],
            },
        ),
        migrations.CreateModel(
            name="EffectModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_positive", models.BooleanField()),
                (
                    "magnitude_by_class",
                    models.JSONField(
                        help_text="Strength text (e.g. '+30%') indexed by effect_power - 1."
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="wormholes.effect",
                    ),
                ),
            ],
            options={
                "ordering": ["effect", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="effectmodifier",
            constraint=models.UniqueConstraint(
                fields=("effect", "name"), name="unique_effect_modifier_name"
            ),
        ),
    ]
